services:
  web:
    image: ghcr.io/calagopus/bot:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DATABASE_URL=sqlite:///var/lib/bot/calagopus_bot.db
      - DATABASE_MIGRATE=true
      - PORT=8000
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
    volumes:
      - ./data:/var/lib/bot
    ports:
      - 9070:8000
